<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Linka.Cargo.BusinessLayer\Linka.Cargo.BusinessLayer.csproj" />
    <ProjectReference Include="..\Linka.Cargo.DataAccessLayer\Linka.Cargo.DataAccessLayer.csproj" />
    <ProjectReference Include="..\Linka.Cargo.DtoLayer\Linka.Cargo.DtoLayer.csproj" />
    <ProjectReference Include="..\Linka.Cargo.EntityLayer\Linka.Cargo.EntityLayer.csproj" />
  </ItemGroup>

</Project>
